### ISSUE TITLE
NVIDIA Driver installation fails

### ISSUE THREAD

**Issue by ThePooN** [mviereck/x11docker#162] opened 2019-05-22 21:50 UTC
The NVIDIA driver 430.14 installer fails to extract itself apparently. It simply says "Extraction failed" at line 1364 of the logs: https://pastebin.com/ULdET12T  
I have 10GB free on my root partition.

Running Docker 18.09.6-ce on Arch Linux with NVIDIA drivers 430.14.

**Comment by mviereck** [comment] 2019-05-23 19:31
Thank you for reporting this!

I can confirm the issue, I'll look into it. 

Curiously, [creating a base image](https://github.com/mviereck/x11docker/wiki/NVIDIA-driver-support-for-docker-container#nvidia-driver-base-image) does not fail, although the installation is not obviously different.

**Comment by ThePooN** [comment] 2019-05-23 19:45
Ah, thanks. I'll look into that as a workaround!

**Comment by mviereck** [comment] 2019-05-24 06:44
The issue is fixed now.

Per default x11docker sets docker option `--security-opt=no-new-privileges`.
Previously this was no issue for installing NVIDIA drivers. Maybe something has changed within docker, and this option forbids more than before. I am not sure.

Now x11docker does not set this option anymore if an NVIDIA driver has to be installed.
I am not lucky about this because it is a strong security feature otherwise.

Please try out the latest master version of x11docker.

**Closed** 2019-06-07 14:35 UTC
Labels: bug

**Comment by mviereck** [comment] 2019-07-11 16:31
x11docker release v6.0.0 includes the fix for this issue.

**Comment by mviereck** [comment] 2019-12-10 09:16
@ThePooN Could you please run a test for me?

I recently did some code changes that affect the automated NVIDIA driver installation (compare https://github.com/mviereck/x11docker/issues/198#issuecomment-563385184).
To my surprise I found that the issue of this ticket does not occur anymore.

To fix the issue I had to drop `--security-opt=no-new-privileges` although it worked before. Now it seems to work again. I've downgraded to Docker 18.09.6-ce, also no issue.
I assume it has been a bug somewhere in the docker dependencies that has been fixed meanwhile.

This command should fail if the issue is still present:
```
x11docker --gpu --init=systemd --newprivileges=no x11docker/check glxinfo | grep renderer
```
If the command succeeds, it should show the name of your graphics card.

**Comment by ThePooN** [comment] 2019-12-10 15:37
Works successfully!

Thanks :)

**Comment by mviereck** [comment] 2019-12-10 15:41
Thank you for the test!
Now the NVIDIA setup will run with much less privileges than before, great.
