### ISSUE TITLE
No access to display (the one generated by x11docker) with incrontab

### ISSUE THREAD

**Issue by symio** [mviereck/x11docker#393] opened 2021-11-25 15:52 UTC
Hello,
First thank you very much for x11docker !

We are working on a project who launch desktop debian on demand based upon x11docker, x11docker/lxqt, x11docker/lxde and xpra.
We are able to generate docker containers and we already have several images working.
We are able to run a vm by lauching it from a tty (ssh on the server) and need to automatize it (we have developped a solution around incrontab)

Sadly, x11docker is not able to access the display it create (:101 ... :1xx) and shutdown the docker image if the launching script is run from incrontab system.
The exact same launching script launched from a tty (with the same debian user) by an human user connected to server by ssh works like a charm.

launcher script is simple as : 

```
#!/bin/bash
echo "from launcher script : x11docker"

export XDG_RUNTIME_DIR=/run/user/1000 # needed for launching from incron

read Xenv < <(/usr/bin/x11docker -q --init=tini --xvfb --size=1980x1200 --lang=fr --keymap fr-latin9 --pulseaudio --home --homebasedir={VM_STORE_PATH}/{VM_NAME}/{HOME_SUBFOLDER} {VM_NAME}_wallet:latest)
# vars in {***} are substitued before launching no bug here

echo $Xenv && export $Xenv

echo "from launcher script : xpra now"

XPRA_DISPLAY_FD_TIMEOUT=30
XPRA_VFB_WAIT=20

/usr/bin/xpra start-desktop $DISPLAY --use-display  --html=on --bind-{BIND_TYPE}=0.0.0.0:{PORT_NUMBER} --start-via-proxy=no --pulseaudio {SSL_CONFIG}
```
log of failling launch for option -D : https://pastebin.com/Lwx4xxDi (line 239 and following "(lxsession:190): Gtk-WARNING **: 14:53:54.927: cannot open display: :102" is the shtdown of docker image

log of running ("manual" launch) : https://pastebin.com/6EQcwSVL

And another faillure log (full) : https://pastebin.com/7ZeHP6kV

Thank you very much for the help you could give to us.

Best Regards

**Comment by mviereck** [comment] 2021-11-25 16:14
The error already appears at the begin of the logs:
```
from launcher script : x11docker
DEBUGNOTE[14:53:45,221]: traperror: Command at Line 6668 returned with error code 1:
  env LANG=C tty 2>&1
  9067 - ::check_host::main::main
DEBUGNOTE[14:53:45,230]: time to say goodbye (traperror)
```
Option `-D, --debug` is very strong if a command fails and terminates x11docker in that case.
Here it is command `tty` that fails if not running on a tty.
I've commited a fix that catches a failing `tty` command.

**Comment by symio** [comment] 2021-11-26 07:04
Hello, 

Yes i see -D is blocking that's why, in the others logs, the launch is attempted as -q but the result is still the same.
I'll update the script with your latest patch and give you some return later on the day.

So it could not work outside of a TTY ? 
Do you now how to be in a TTY when using something like incrontab ? (it's like cron but with inotify and triggers on filesystem modifications ; in our case when a vm is attended to be launch)

Maybe if we do the work of x11docker directly with docker (we have a docker runner implemented in our project it is with this we build the containers first) but i really doubt i can access to display.

I'm thinking about -xonly, -getenv solution to better integrate xpra with the launch but not sure how to do it too.

Btw Thank you for reactivity and answers,

**Comment by mviereck** [comment] 2021-11-26 07:33
> Yes i see -D is blocking that's why

Please run further tests without `--debug`. Once x11docker runs as expected, try again with `--debug`.

> So it could not work outside of a TTY ?

x11docker should run without a tty, noteable with `--xvfb`.

Thinking over it, the failing `tty` command might not be the reason for your issue, because it runs in a subshell and should not terminate x11docker if failing. However, let's debug without `--debug` for now

> I'm thinking about -xonly, -getenv solution to better integrate xpra with the launch but not sure how to do it too.

x11docker prints `DISPLAY` and `XAUTHORITY`. You would need to set both variables in your docker command.
Also share the file in `XAUTHORITY` with the container.

**Comment by symio** [comment] 2021-12-12 17:21
Hello,

Sorry for the delay in response but I had so much to do ...
I carried out many tests but without any notable progress.
There is no longer the TTY detection x11docker error.
I see the Docker container launch and immediately shut down.
A bit as if it were in "command launch" mode.
I even tried to keep the script open with a loop but no effect.
Below is the script used (no more sound, no more xpra without container, it's not useful for the moment and the wait loop) as well as the logs in silent mode and in debug mode.

- Launch script: https://pastebin.com/rcTTgswh
- x11docker log (debug mode): https://pastebin.com/9RBG1Wmk
- x11docker log (quiet): https://pastebin.com/9wa38Jcf
- my debug (with xauth and display): https://pastebin.com/mnxTx3iu

Please tell me if you think of a Docker or other problem because I really do not see why it does not work.
The Xauthority file (finally the files because I find 3 in ~ / .cache / x11docker / xxxxxx) is indeed present at the url indicated in the logs.

Maybe i could integrate xpra on the launching command line but i can't figure it instead calling xpra after gaining the display number.
I've tried but did not make it to work.

ps: in the final version I would not need the debug, the x11docker logs will be more than sufficient.

Best regards,

**Comment by mviereck** [comment] 2021-12-19 17:58
I also can't see any obvious issue in the logs except that LXDE cannot access the display.
However, some commands on host like `xrandr` can access it.

Some options you could try:
`--no-auth` to disable cookie authentication
`--xoverip` for TCP based X connection instead of a unix socket
`--cap-default` to run a less restricted container

**Comment by symio** [comment] 2022-01-06 10:36
Hello and let me wish you the best for 2022,

I tried the indicated options and nothing get better.
Key problem is ```xinit: connection to X server lost``` and ```(lxsession:186): Gtk-WARNING **: 11:05:16.136: cannot open display: 172.17.0.1:xxx``` (here xxx display number is good (101, 102 ...)).

I, once, thought xvfb has crashed but when i try to replay the "X server command" generated (by and found) in debug log Xvfb says the server with this display number is running.

I re-past you some sample logs (with and without -D option but result is the exact same).

I tried all X-servers possible, i have also tried a lot of launching scripts derivations without any better results. 
Launching scripts still works fine when launched in a "real terminal" by human action.

I am now working on copying x11docker actions directly in symfony process classes in hope to get out of the vty limitations (btw sf processes will not work better in my opinion).

Only last question : do you think you can do something on you're side ? 
If not, and if sf procs do not give us automation, we will probably work on some different workflow with human powered pre-launchs and try to not make containers hangs-down when user close his remote session but we really try to avoid this.

X11docker.log pastes : 
* x11docker.log_without_xoverip : https://pastebin.com/WzGJdsBb
* x11docker.log_with_xoverip : https://pastebin.com/uG4mBJjH
* x11docker.log_all_options : https://pastebin.com/51weqA3Y
* x11docker.log_all_options_no_debug : https://pastebin.com/j5b2unU1

Best regards

**Comment by mviereck** [comment] 2022-01-06 12:53
My best wishes for you, too! :-)

I've set up `incron` on my system to to test your setup.
I found something quite confusing during my test runs:

I can reproduce your failures with a similar setup.
But I succeed in incrontab if running a host executeable:
```
x11docker --xvfb --exe xterm
```
But if I check `ls /tmp/.X11-unix`, the socket of the new X server does not appear!
So if sharing a non-existing socket with a container, it obviously must fail to start.

My suspection:
It seems incrontab somehow hides `/tmp/.X11-unix` or provides an alternate path of `/tmp` to its clients.
I have no idea why it should do that, or where this alternate `/tmp` might be located.
However, docker does not see this alternate `/tmp`.

**Comment by mviereck** [comment] 2022-01-06 13:01
One workaround:
`podman` does not run a system daemon, so it sees the same `/tmp` as the rest of the incron script.
If you run x11docker with `--backend=podman`, the container startup succeeds.

**Comment by symio** [comment] 2022-01-06 13:05
I'll immediately test this thank you !

**Comment by mviereck** [comment] 2022-01-06 14:29
Yet I've found an bug in `--xvfb` that might cause to fail it. If in doubt, just set option `--size=19020x1200`.

**Comment by symio** [comment] 2022-01-06 15:12
Actually i'm struggling with podman ...
it accept pulling the image from docker-daemon but after a test launch it do not list the images or containers anymore ...
i hate to reboot on linux lol

**Comment by mviereck** [comment] 2022-01-06 15:18
> it accept pulling the image from docker-daemon but after a test launch it do not list the images or containers anymore ...

Odd. It has a different storage location for images and containers than docker, but otherwise it basically works the same way.
For example, after `podman pull IMAGE` you should see the image with `podman images`. For containers `podman ps -a`.
Note that podman works for the current user, so `podman images` as regular user gives you a different result than `sudo podman images`. The images and containers are stored in `HOME` of the command calling user.

No reboot should be needed, especially because podman does not run a system daemon.

**Comment by symio** [comment] 2022-01-06 15:21
Yes i have pull it (tranfer image from local docker daemon to podman) but podman get stuck and blocked my computer ... bad start

**Comment by symio** [comment] 2022-01-06 15:22
even x11docker log was not written !

**Comment by mviereck** [comment] 2022-01-06 15:24
Please pull directly with `podman pull`. In upcoming x11docker v7.0.0 x11docker no longer pulls missing images itself, too much hassle.

**Comment by symio** [comment] 2022-01-07 13:06
I still have display issues in my mixed env (docker + podman).
I will use the next days to rewrite my code to take full usage of podman and i'll get back to report to you the results (after deploy and test on a new testing server with clean config)

**Comment by mviereck** [comment] 2022-01-07 14:25
One side note: Currently you grab the environment variables with `read Xenv < <(x11docker ...)`.
Upcoming x11docker version 7.0.0 (currently in master / beta) replaces former option `--showenv` with `--printenv [=FILE]` that allows to write the environment variables into a file. This as an alternative to the current `read ...` setup.

**Comment by symio** [comment] 2022-01-08 13:53
Hello,

What i did now : 
Startup script (launched from incrontab (same error or isolation from symfony process)) :
```C
#!/bin/bash
read Xenv < <(/usr/bin/x11docker --backend=podman --xvfb --size=1920x1200x24 --lang=fr --no-auth --keymap fr-latin9 --home \
--homebasedir=/home/symio/Developpement/xxxxxxxx/MBDV/xxxxxxxx_xxxxxxxx/wp-content/plugins/xxxxxxxx_xpra_docker_admin/system_admin-tpls/vms/xxxxxxxx_nz6grn/home localhost/xxxxxxxx_nz6grn_wallet:latest)
export XDG_RUNTIME_DIR=/run/user/1000
export DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
export XPRA_DISPLAY_FD_TIMEOUT=30
export XPRA_VFB_WAIT=20
echo $Xenv && export $Xenv
env -i python3 /usr/bin/xpra start-desktop $DISPLAY --use-display  --html=on --bind-tcp=0.0.0.0:10033 --start-via-proxy=no --pulseaudio

```

I tried short or long names (xxxxxxxx_nz6grn_wallet:latest or localhost/xxxxxxxx_nz6grn_wallet:latest) witch is a know image in podman (imported from docker)

When reading x11docker logs:
* /tmp/.X11-unix/X102 is not found lines 1725 and 1732 of both logs files, when i manually run the xvfb command and ls _al /tmp/.X11-unix i found X102= : 
![image](https://user-images.githubusercontent.com/52332/148646313-5938171f-c9f3-4c7d-bf04-92428e1dfcd4.png)

* I got this x11docker error at line 1729 : x11docker ERROR: "Startup of podman failed. Did not receive a container ID. "

* After making a dockerrc file by copying the one provided in logs (without the line numbers), mkdir -p /home/symio/.cache/x11docker/localhost-xxxxxxxx_nz6grn_wallet-latest-47179813176/share
* After copying the dockerrc to /home/symio/.cache/x11docker/localhost-xxxxxxxx_nz6grn_wallet-latest-47179813176/share/containerrc
* After launching xvfb with the command in logs
* When i run the podman command and do a podman logs x11docker_X102_localhost-xxxxxxxx_nz6grn_wallet-latest_47179813176 it says it do not access to /home/symio/.cache/x11docker/localhost-xxxxxxxx_nz6grn_wallet-latest-47179813176/
![image](https://user-images.githubusercontent.com/52332/148646393-504298a5-0e73-4263-bf57-4a0fa44ccdf3.png)

But i'm maybe miss some steps.

Joined logs files (very similar) :
* x11docker.log_podman_shortimagename : https://pastebin.com/YHR332st
* x11docker.log_podman_longimagename : https://pastebin.com/1P51Che7

I'm working on the clean env to adapt my docker-compose generation and running it adapted to podman without docker installed

Ps1 : No problem for generating and pulling the image independently of x11docker this is what i already do from sf process classes
Ps2: Good news for --printenv it will be easier to control independent commands from sf process i have struggle a bit how to get those data from initial command line and have to admit to stay on the read / export system

**Comment by mviereck** [comment] 2022-01-09 14:04
Now I get errors, too, although it worked the first time I've testet it. Not sure what is different now.
In my tests I found that Xvfb complains that `/tmp/.X11-unix` is not owned by root.
I assume that Xvfb did not create a socket.
 (Yet another incrontab-tmp issue. Maybe incrontab does some filesystem namespacing for obscure reasons. Could not found anything about this in the man pages of incrontab.)

I succeeded with adding option `--xoverip` that does not need a socket.

Just out of curiosity, is `incrontab` really essential for your setup? It sounds a bit odd that some sort of file access should run a containerized GUI. For me the obscure `/tmp` would already be a reason to rather work with `incrontab`.

**Comment by symio** [comment] 2022-01-09 14:26
ok i'll try xoverip in a couple of hours

absolutely not, incrontab was a workaround attempt because symfony process classes have the same filesystem isolation issues
So if it work with xoverip with incron tab it's good, if it's work with xoverip over symfony process classes (https://symfony.com/doc/current/components/process.html) it's even better for us because it will be fully controled by my php classes and will be better for us. (especially with --printenv who will provide me the env params in php vars via a parsed file)

I think filesystem isolation is for enhanced security (witch i can understand but not with usage killing, access to sockets in tmp is legit in our case) but as always so such security kills usage

**Comment by symio** [comment] 2022-01-10 07:37
Hum, at first attempt i got (lxsession:179): Gtk-WARNING **: 15:28:25.897: cannot open display: 172.17.0.1:101

With options  --cap-default --backend=podman --xoverip --no-auth --xvfb --size=1920x1200 --lang=fr  --keymap fr-latin9 --home \
--homebasedir (with or without cap-default, no-auth, xoverip doesnt make a change)

I always get the errors and not able to make it work last log : https://pastebin.com/bJWeK6dH where i can see : 
* line 1870, 1874 :  (lxsession:169): Gtk-WARNING **: 08:23:15.716: cannot open display: 172.17.0.1:104 
* 1925, 1926 :   Lost child of dockerrc (dockerstopshell):
    bash(1572747)
* 1972 : DEBUGNOTE[08:23:17,265]: Removing container x11docker_X104_localhost-xxxxxxxx_nz6grn_wallet-latest_99384678752
    7431b783f0e4262e5b824eaa5f1244e616212f9391d1b9a490ca3ac867360767

I'll try replace incrontab invocation with launching script invocation right now and report but i'm pretty sure the result will be the same

**Comment by mviereck** [comment] 2022-01-10 11:17
Very odd.
This is my current working test script:
```
#! /bin/bash
log=/home/lauscher/incrontest/log
rm $log
exec 1>>$log 2>>$log
date 

read Xenv < <('x11docker' '--debug' '--backend=podman' '--xvfb' '--showenv' '--size=1920x1200' docker.io/x11docker/fvwm )

echo "$Xenv"

#mount | grep tmp 

ls -la /tmp 
ls -la /tmp/.X11-unix 
```
I follow the output with `tail -F log`. Running `ps aux | grep fvwm` shows me a running fvwm desktop session. A `killall fvwm` stops the x11docker session.

Note that it works even without `--xoverip` or `--no-auth`. And `ls -la /tmp/.X11-unix ` shows me a socket.
Is it possible that symfony adds issues here?

> line 1870, 1874 : (lxsession:169): Gtk-WARNING **: 08:23:15.716: cannot open display: 172.17.0.1:104

This is the only important issue here. Following messages like xinit errors and removing container are just follow-ups caused by terminating x11docker.

This part of the log reports that the container command has terminated; this causes x11docker to terminate everything else, too:
 ```
DEBUGNOTE[08:23:15,757]: storepid(): Stored pid '1572084' of 'pid1pid': 
DEBUGNOTE[08:23:15,758]: watchpidlist(): PID 1572084 has terminated
DEBUGNOTE[08:23:15,760]: time to say goodbye (watchpidlist 1572084)
```
> I think filesystem isolation is for enhanced security (witch i can understand but not with usage killing, access to sockets in tmp is legit in our case) but as always so such security kills usage

Without any documentation of this behaviour I'd rather call is obscurity than security. ;-)
However, incron seems to be abandoned, it hasn't seen activity for years. So the ticket won't get an answer either. Likely it is better not to use it. It has been removed from debian stable already. A bit sad, looks like a nice tool.

> -I'll try replace incrontab invocation with launching script invocation right now and report but i'm pretty sure the result will be the same-
>I just did it, no better results.

Same "cannot open display" issue?
Could you run my test script above in symfony? (Adjust line `log=...`)

**Comment by symio** [comment] 2022-01-10 11:43
I ran my launcher both from incron and process class, i'll try your launching this afternoon


-------- Message original --------
De: mviereck ***@***.***>
Envoyé: Mon Jan 10 12:18:01 GMT+01:00 2022
À: mviereck/x11docker ***@***.***>
Cc: Huby Franck ***@***.***>, Author ***@***.***>
Sujet: Re: [mviereck/x11docker] No access to display (the one generated by x11docker) with incrontab (Issue #393)

Very odd.
This is my current working test script:
```
#! /bin/bash
log=/home/lauscher/incrontest/log
rm $log
exec 1>>$log 2>>$log
date 

read Xenv < <('x11docker' '--debug' '--backend=podman' '--xvfb' '--showenv' '--size=1920x1200' docker.io/x11docker/fvwm )

echo "$Xenv"

#mount | grep tmp 

ls -la /tmp 
ls -la /tmp/.X11-unix 
```
I follow the output with `tail -F log`. Running `ps aux | grep fvwm` shows me a running fvwm desktop session. A `killall fvwm` stops the x11docker session.

Note that it works even without `--xoverip` or `--no-auth`. And `ls -la /tmp/.X11-unix ` shows me a socket.
Is it possible that symfony adds issues here?

> line 1870, 1874 : (lxsession:169): Gtk-WARNING **: 08:23:15.716: cannot open display: 172.17.0.1:104

This is the only important issue here. Following messages like xinit errors and removing container are just follow-ups caused by terminating x11docker.

This part of the log reports that the container command has terminated; this causes x11docker to terminate everything else, too:
 ```
DEBUGNOTE[08:23:15,757]: storepid(): Stored pid '1572084' of 'pid1pid': 
DEBUGNOTE[08:23:15,758]: watchpidlist(): PID 1572084 has terminated
DEBUGNOTE[08:23:15,760]: time to say goodbye (watchpidlist 1572084)
```
> I think filesystem isolation is for enhanced security (witch i can understand but not with usage killing, access to sockets in tmp is legit in our case) but as always so such security kills usage

Without any documentation of this behaviour I'd rather call is obscurity than security. ;-)
However, incron seems to be abandoned, it hasn't seen activity for years. So the ticket won't get an answer either. Likely it is better not to use it. It has been removed from debian stable already. A bit sad, looks like a nice tool.

> -I'll try replace incrontab invocation with launching script invocation right now and report but i'm pretty sure the result will be the same-
>I just did it, no better results.

Same "cannot open display" issue?
Could you run my test script above in symfony? (Adjust line `log=...`)

**Comment by symio** [comment] 2022-01-10 13:53
Ok, make 2 run test with your launching script and incrontab (because our needs here is automate the vm launching)

one with no xoverip and guess what ? it doesn't see the /tmp/X11*** : https://pastebin.com/5cXBZ1w0
one with xoverip and it dosen't see the 172.17.0.1:115 display : https://pastebin.com/dvuZFxx7

In thoses file i put for you in order (separate by "## **************" lines) :
* the incrontab command and incrontab launch script
* the launching script content (yes i prefer touch and truncate instead of rm when tailling files)
* commands launched localy after running attempt
* the ~/incrontest/log file (i named it x11docker_log)
* debug of my incrontab prelaunch script
* x11docker log file

How my incrontab system work : 
* incrontab looks for entries in a directory
* incrontab prelaunch script will launch script with name as string in the pushed file script must be executable under a directory of same name of the pushed file
exemple : 
* directory for events : /home/symio/Developpement/xxx/MBDV/xxx_xxx/wp-content/plugins/xxx_xpra_docker_admin/system_admin-tpls/vms/incron/vmsToLaunch/
* base path for "vms" : /home/symio/Developpement/xxx/MBDV/xxx_xxx/wp-content/plugins/xxx_xpra_docker_admin/system_admin-tpls/vms/incron/vmsToLaunch/../../
* in this base path a directory named "xxx_nz6grn" with your launch script executable bash named "lance.ok.sh.new"
* write "lance.ok.sh.new" (without quotes) in a file named "xxx_nz6grn" 
* copy it to /home/symio/Developpement/xxx/MBDV/xxx_xxx/wp-content/plugins/xxx_xpra_docker_admin/system_admin-tpls/vms/incron/vmsToLaunch/ (not with term, in my case with php symfony process classes)
* it failed

**Comment by symio** [comment] 2022-01-10 13:57
and when running the launching script directly from term it work

**Comment by symio** [comment] 2022-01-10 14:03
copy paste bug last log from launching here : 
Mon Jan 10 14:34:14 CET 2022
[32mx11docker note:[0m Option --showenv is deprecated. Please use option --printenv instead.

[33mx11docker WARNING:[0m User symio is member of group docker.
  That allows unprivileged processes on host to gain root privileges.

Failed to connect to bus: $DBUS_SESSION_BUS_ADDRESS and $XDG_RUNTIME_DIR not defined (consider using --machine=<user>@.host --user to connect to bus of other user)
DISPLAY=172.17.0.1:115 XAUTHORITY=/home/symio/.cache/x11docker/docker-io-x11docker-fvwm-21654746084/share/Xauthority.client
total 16
drwxrwxrwt  4 root  root  4096 Jan 10 14:34 .
drwxr-xr-x 20 root  root  4096 Oct 23 12:22 ..
drwxrwxrwt  2 symio symio 4096 Jan 10 14:34 .X11-unix
drwx------  3 symio symio 4096 Jan  6 16:23 containers-user-1000
total 8
drwxrwxrwt 2 symio symio 4096 Jan 10 14:34 .
drwxrwxrwt 4 root  root  4096 Jan 10 14:34 ..
[fvwm][main]: <<ERROR>> can't open display 172.17.0.1:115

**Comment by symio** [comment] 2022-01-10 14:04
it sees /tmp/.X11** i think it's inside the container where the bug is

**Comment by mviereck** [comment] 2022-01-10 17:21
> it sees /tmp/.X11** i think it's inside the container where the bug is

In both logs `/tmp/.X11-unix` is empty, different from my test runs.
I wonder why there is no debug output in your x11docker_log although `--debug` is enabled. I get a lot of messages here.

I think it is time to give up `incron`. 

A proposal: use `inotify-wait`.
Example:
```
touch watchfile
inotify-wait -e access ./watchfile && ./x11docker_xpra_script
```
As soon as someone reads file `./watchfile` the script `./x11docker_xpra_script` is executed. `/tmp` is the real tmp of the system.

**Comment by mviereck** [comment] 2022-01-11 09:11
Yesterday, after some tests with `incron`, I had issues with podman *outside* of incron. I could fix them with deinstalling `icron` and rebooting the system.

It seems to me that `incron` causes severe damage to the filesystem namespaces and recommend to not use it at all. I might be wrong, but I suspect `incron` to do damage.

If you encounter further issues with x11docker, please deinstall `incron` first and reboot your system.

**Comment by symio** [comment] 2022-01-11 09:45
I don't had time to test inotify this morning (too many admin tasks) i'll do it as soon as possible.
Like i said most important for us is automation with inotify or whatever we are not specifically attached to incron 
On other hand we mostly prefer docker as podman because we use portainer for non tech admins to follow loads of containers so if it works with inotify we will not install incron in prod. (and because all code is for docker with docker-compose and docker commands to retrieve images names / status in admin interface so changing to postman would deal a bit of work i didn't do so far)

i'll report to you here as soon as i can make changes and test with inotify

**Comment by mviereck** [comment] 2022-01-11 10:28
> On other hand we mostly prefer docker as podman 

Using `podman` instead of `docker` was just a workaround to circumvent the `/tmp` limitations of `incron`.
With other solutions like `inotify-wait` you are free to use `docker` again.

**Comment by symio** [comment] 2022-01-12 13:36
Ok ! a big step has been made !

I got your fvwm to run !
inoticoming (because i will have severals vms not just one and need to watch directory for launchs it's more easy that way), a startup script to run it as a daemon just like incron, no xoverip, no podman (and with --debug !)
Only error is : sh: fvwm-menu-desktop: not found

x11docker_log (launching log in incrontest) : https://pastebin.com/wEaf6kP3

system daemon like script (in /etc/init.d) as like : 
```
#!/bin/bash

xxxPath="/home/symio/Developpement/xxx/MBDV/xxx_xxx/wp-content/plugins/xxx_xpra_docker_admin/system_admin-tpls/vms/"
incronPath="${xxxPath}incron/"
logPath="${xxxPath}launching_logs/"
vmToLaunchPath="${incronPath}vmsToLaunch"

case "${1}" in
    start)
        touch ${logPath}inoticoming_xxx.pid
        touch ${logPath}inoticoming_xxx.log
        echo "start inoticoming_xxx service" >> ${logPath}inoticoming_xxx.log
        inoticoming --logfile "${logPath}inoticoming_xxx.log" --pid-file "${logPath}inoticoming_xxx.pid" ${vmToLaunchPath} ${incronPath}launchVm.sh "${vmToLaunchPath}/" {} 'IN_CLOSE_WRITE' 8 \;
    ;;

    stop)
        kill -15 $(< ${logPath}inoticoming_xxx.pid tee)
    ;;

    restart)
        ${0} stop
        sleep 1
        ${0} start
    ;;

    *)
    echo "Usage: ${0} {start|stop|restart}"
    exit 1
    ;;
esac
```
Also set ``` sudo update-rc.d inoticoming_xxx ``` and ``` sudo systemctl daemon-reload ``` with chmod +x and ``` sudo service inoticoming_xxx start ```

pre-launch script is : 
```
#!/bin/bash

globalLogFile='/home/symio/Developpement/xxx/MBDV/xxx_xxx/wp-content/plugins/xxx_xpra_docker_admin/system_admin-tpls/vms/launching_logs/inoticoming_xxx.log'
incronTabFilePath="$1"
vmPath="$incronTabFilePath../../"
incronTabFile="$incronTabFilePath$2"
scriptName=`cat $incronTabFile`
vmScriptFull=($vmPath$2/$scriptName)
outputFile=($vmPath$2/launchingRes.log)

if test -f "$incronTabFile"; then
    touch $outputFile
    truncate -s0 $outputFile

    echo "***"  >> "${globalLogFile}"
    echo "0:$0" >> "${globalLogFile}"
    echo "1:$1" >> "${globalLogFile}"
    echo "2:$2" >> "${globalLogFile}"
    echo "3:$3" >> "${globalLogFile}"
    echo "4:$4" >> "${globalLogFile}"
    echo "tous:$*" >> "${globalLogFile}"
    echo "incronTabFilePath:$incronTabFilePath" >> "${globalLogFile}"
    echo "vmPath:$vmPath" >> "${globalLogFile}"
    echo "incronTabFile:$incronTabFile" >> "${globalLogFile}"
    echo "scriptName:**$scriptName**" >> "${globalLogFile}"
    echo "vmScriptFull:$vmPath$2/$scriptName" >> "${globalLogFile}"
    echo "***" >> "${globalLogFile}"

        $vmScriptFull >> $outputFile 2>&1 
        rm $incronTabFile
else
        echo "Nothing to do here except avoiding run at rm !" >> "${globalLogFile}"
fi
# because inoticoming fork and close at each startup run it again
service inoticoming_xxx start
```
did a ```echo "lance.ok.sh.new" > incron/vmsToLaunch/xxx_nz6grn``` (dirname where launching script "lance.ok.sh.new" is)
I just set --host-user=symio and --backend=docker in my launching script and (tadaaaaa) : 
```
CONTAINER ID   IMAGE                   COMMAND                  CREATED          STATUS          PORTS     NAMES
9050b5a2ee98   x11docker/fvwm:latest   "env /usr/local/bin/…"   42 seconds ago   Up 41 seconds             x11docker_X106_x11docker-fvwm-latest_93320597264
```

Time to package all of this for my generated vms and check if xpra get the connection.

When everything will be ok i'll close this issue

**Comment by mviereck** [comment] 2022-01-12 17:10
Great! I am happy to hear this.

**Comment by mviereck** [comment] 2022-01-30 10:17
Closing due to solved issue.
If further issues or questions arise, please open a new ticket.

**Closed by mviereck** 2022-01-30 10:17 UTC
Labels: not an x11docker bug
