### ISSUE TITLE
pulseaudio not creating cookie or socket in ubuntu container

### ISSUE THREAD

**Issue by satmandu** [mviereck/x11docker#238] opened 2020-04-01 13:33 UTC
pactl isn't being run either?

Dockerfile.zoom:
```
FROM ubuntu:20.04
ENV DEBIAN_FRONTEND=noninteractive
ENV LANG en_US.UTF-8
RUN apt update && apt-get install -y --no-install-recommends \
      locales && \
      echo "$LANG UTF-8" >> /etc/locale.gen && \
      locale-gen 
RUN packages="                                               \
                                                             \
      alsa-utils \
      ca-certificates                                          \
      va-driver-all  \
      curl sudo desktop-file-utils \
      libpulse0 \ 
      locales \
      mesa-utils \
      mesa-utils-extra \
      libvpx6 \
      pulseaudio                                               \
      pavucontrol \
      libcec4	\
      cec-utils \
      libnss3 \
      libnss3-tools \
      at-spi2-core \
      dbus \
      dbus-x11 \
      procps \
      psutils \
      systemd  systemd-sysv\
      gnome-session\
      cheese \
      gedit \
      gnome-control-center \
      gnome-terminal \
      gnome-tweak-tool \
      nautilus \
      gnome-shell-extension-dash-to-panel \
      gnome-shell-extension-desktop-icons" && \
apt-get install -y --no-install-recommends software-properties-common && \
(ln -fs /usr/share/zoneinfo/America/New_York /etc/localtime && export DEBIAN_FRONTEND=noninteractive && apt-get install -y tzdata && dpkg-reconfigure --frontend noninteractive tzdata ) && \
    apt-get install -y --no-install-recommends $packages  && \
	apt-get dist-upgrade -y && \
	apt-get -y purge software-properties-common                   && \
    apt-get -y --purge autoremove                         && \
    rm -rf /var/lib/apt/lists/*
RUN curl -OL https://zoom.us/client/latest/zoom_amd64.deb && \
    (apt update || true ) && \
    apt install gdebi -y && \
    gdebi --n ./zoom_amd64.deb  && apt install -f -y
# setup entry point
#COPY entrypoint.sh /usr/local/bin
#ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
CMD gnome-session
```
cmdline:
```
docker build --pull  -t satmandu-kodi -f Dockerfile.zoom .
cd ~zoom && x11docker --xorg --pulseaudio=socket  \
            --fullscreen \
            --gpu                                  \
            --webcam \
            --home=/home/zoom      \
            --group-add=audio \
            --group-add=dialout \
                --group-add=zoom \
                --user zoom \
                --init=systemd \
       --    -- satmandu-zoom
```

```
root@30be48821c49:/x11docker# env
HOSTNAME=30be48821c49
PWD=/x11docker
XAUTHORITY=/x11docker/Xauthority.client
container=docker
HOME=/root
LANG=en_US.UTF-8
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:
PULSE_COOKIE=/x11docker/pulseaudio.cookie
TERM=xterm
DISPLAY=:111
SHLVL=1
XDG_RUNTIME_DIR=/tmp/XDG_RUNTIME_DIR
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PULSE_SERVER=unix:/x11docker/pulseaudio.socket
DEBIAN_FRONTEND=noninteractive
OLDPWD=/tmp
_=/usr/bin/env
root@30be48821c49:/x11docker# ls -aFl /x11docker/
total 148
drwxr-xr-x  2 root 0     16 Apr  1 09:29 ./
drwxr-xr-x 18 root 0     28 Apr  1 09:29 ../
-rw-rw-rw-  1 root 0    489 Apr  1 09:29 container.environment
-rw-rw-rw-  1 root 0  14588 Apr  1 09:29 container.log
-rwxr-xr-x  1 root 0   5986 Apr  1 09:29 containerrc*
-rw-r--r--  1 root 0  14798 Apr  1 09:29 containerrootrc
-rw-r--r--  1 root 0   3536 Apr  1 09:29 libc.localtime
prw-rw-rw-  1 root 0      0 Apr  1 09:29 message.fifo|
-rw-rw-rw-  1 root 0   7176 Apr  1 09:30 stderr
-rw-rw-rw-  1 root 0     77 Apr  1 09:29 stdout
-rw-rw-rw-  1 root 0    763 Apr  1 09:29 store.info
-rw-r--r--  1 root 0  46811 Apr  1 09:31 systemd.journal.log
-rw-r--r--  1 root 0      0 Apr  1 09:29 timetosaygoodbye
prw-r--r--  1 root 0      0 Apr  1 09:29 timetosaygoodbye.fifo|
-rw-rw-rw-  1 root 0 188727 Apr  1 09:31 x11docker.log
-rw-r--r--  1 root 0    108 Apr  1 09:29 Xauthority.client
```

```
DEBUGNOTE[11:39:47,265]: Docker command:
  docker run --tty --rm --detach \
  --name x11docker_X101_satmandu-zoom_69186422236 \
  --user 1004:1005 \
  --env USER=zoom \
  --userns host \
  --group-add 29 \
  --group-add 20 \
  --group-add 1005 \
  --group-add 44 \
  --group-add 109 \
  --cap-drop ALL \
  --security-opt no-new-privileges \
  --security-opt label=type:container_runtime_t \
  --volume '/usr/bin/docker-init':'/usr/local/bin/init':ro \
  --tmpfs /run --tmpfs /run/lock \
  --volume '/home/zoom/.cache/x11docker/satmandu-zoom-69186422236/share':'/x11docker':rw \
  --volume '/home/zoom':'/home/zoom':rw \
  --device '/dev/ttyACM0':'/dev/ttyACM0':rw \
  --device '/dev/dri':'/dev/dri':rw \
  --device '/dev/vga_arbiter':'/dev/vga_arbiter':rw \
  --device '/dev/video0':'/dev/video0':rw \
  --device '/dev/video1':'/dev/video1':rw \
  --volume '/run/udev/data':'/run/udev/data':ro \
  --volume '/tmp/.X11-unix/X101':'/X101':rw \
  --volume /home/zoom/.cache/x11docker/satmandu-zoom-69186422236/pulseaudio.client.conf:/etc/pulse/client.conf:ro \
  --workdir '/tmp' \
  --entrypoint env \
  --env 'container=docker' \
  --env 'XAUTHORITY=/x11docker/Xauthority.client' \
  --env 'DISPLAY=:101' \
  --env 'PULSE_COOKIE=/x11docker/pulseaudio.cookie' \
  --env 'PULSE_SERVER=unix:/x11docker/pulseaudio.socket' \
  --env 'XDG_RUNTIME_DIR=/tmp/XDG_RUNTIME_DIR' \
  -- satmandu-zoom /usr/local/bin/init -- /bin/sh - /x11docker/containerrc
```
```
    90  # Environment variables
    91  export 'container=docker'
    92  export 'XAUTHORITY=/x11docker/Xauthority.client'
    93  export 'DISPLAY=:101'
    94  export 'PULSE_COOKIE=/x11docker/pulseaudio.cookie'
    95  export 'PULSE_SERVER=unix:/x11docker/pulseaudio.socket'
    96  export 'XDG_RUNTIME_DIR=/tmp/XDG_RUNTIME_DIR'

```

**Comment by mviereck** [comment] 2020-04-01 16:29
Thank you for the detailed report!
`x11docker --pulseaudio x11docker/check` works here. Is pulseaudio running and `pactl`  installed on your host system?
The latest commits adds some checks for `pactl`, that might help.

**Comment by satmandu** [comment] 2020-04-01 18:17
```x11docker --pulseaudio x11docker/check``` doesn't show pulseaudio working on my system.

If I ssh into the machine I show pulseaudio being started though dbus-daemon by the user doing the ssh... (This is on an ubuntu system.)

Do I need to have X11 already running before I start this?

**Comment by mviereck** [comment] 2020-04-01 19:14
Could you please run a test?
ssh into the machine and execute:
```
pactl load-module module-native-protocol-unix socket=/tmp/testsocket
ls -l /tmp/testsocket
```
This should create and show a pulseaudio socket. If not, does it show an error?

**Comment by satmandu** [comment] 2020-04-01 20:24
```
root@:~# pactl load-module module-native-protocol-unix socket=/tmp/testsocket
Home directory not accessible: Permission denied
Connection failure: Connection refused
pa_context_connect() failed: Connection refused
ls -l /tmp/testsocket
ls: cannot access '/tmp/testsocket': No such file or directory
```

**Comment by mviereck** [comment] 2020-04-01 20:35
You run as root, but pulseaudio does have some issues with that. 
The message is odd: `Home directory not accessible: Permission denied`. Can't you access `/root` as root? Is your `HOME` variable invalid?

Here it works if I switch with `su` to root and run x11docker.
Did you log in as root per ssh immediately?

Maybe a TCP connection works for you:
```
x11docker --pulseaudio=tcp x11docker/check
```

**Comment by satmandu** [comment] 2020-04-01 21:19
FYI:
```
HOME=/root pactl load-module module-native-protocol-unix socket=/tmp/testsocket
Connection failure: Connection refused
pa_context_connect() failed: Connection refused
```
if I do ```sudo -H -s``` first,
```
echo $HOME ; pactl load-module module-native-protocol-unix socket=/tmp/testsocket
/root
Connection failure: Connection refused
pa_context_connect() failed: Connection refused
```

I was having the same issue with pulseaudio=tcp.

**Comment by satmandu** [comment] 2020-04-01 21:21
Also I'm trying to get this started via systemd... so I'm just starting a service which loads a bash script from systemd which runs x11docker with args.

**Comment by satmandu** [comment] 2020-04-01 21:28
Hmm... maybe I need to start pulseaudio from x11docker before running pactl? Is there a proper way to do that so that the sockets are setup correctly?

**Comment by mviereck** [comment] 2020-04-01 21:34
So far it is not an x11docker but a pulseaudio issue, maybe also somehow related to systemd.
I am not sure what is wrong and how to solve it.

Once your system is able to execute `pactl load-module module-native-protocol-unix socket=/tmp/testsocket`, x11docker will work.

Alternatively, you could just use `--alsa` instead of `--pulseaudio` if you don't need special pulseaudio features.

**Comment by satmandu** [comment] 2020-04-01 22:17
Thanks. I've been using the alsa setup to run Kodi flawlessly with x11docker for many months.

**Comment by mviereck** [comment] 2020-04-02 08:52
I cannot reproduce the issue with several combination of ssh/su/sudo. The issue is somewhere in your system. Maybe someone more familiar with pulseaudio can help you.

x11docker at least shows a message now if `pactl` fails.
Sorry that I could not help more than that.
Closing the ticket now.

> Also I'm trying to get this started via systemd... so I'm just starting a service which loads a bash script from systemd which runs x11docker with args.

Please open a new ticket if you have issues concerning this.

**Closed by mviereck** 2020-04-02 08:52 UTC
Labels: not an x11docker bug
