### ISSUE TITLE
docker-for-win: Cannot establish any listening sockets - Make sure an X server isn't already running

### ISSUE THREAD

**Issue by 1138-4EB** [mviereck/x11docker#155] opened 2019-05-09 12:22 UTC
I tried to run the checks #145 after updating to the latest master, and I found the following error:

- Two days ago I started a container in MSYS2 with x11docker 17 commits behind the current master. This container was started with `/path/to/x11docker/x11docker --user=0 -i -- -v /$(pwd)://src -- aptman/dbhi:bionic bash`. Both the container and the X server are still running and working as expected.
- In a different MSYS terminal, I fetched and pulled the latest changes from x11docker and I tried to execute `./x11docker --hostdisplay --gpu x11docker/check`. I get the following error:

![x11check](https://user-images.githubusercontent.com/6628437/57452553-6fd46f80-7264-11e9-91e8-542592453e10.png)

[VCXSrv.100.log](https://github.com/mviereck/x11docker/files/3162047/VCXSrv.100.log)
[x11docker.log](https://github.com/mviereck/x11docker/files/3162050/x11docker.log)

Then, I closed all the containers and X servers, and tried again. The interface of `x11docker/check` is now properly shown.

Last, I started the `aptman/dbhi` container again, and tried to execute `x11docker/check` after it. It fails again.

So, I'd say that some of the latest changes have broken the possibility to start multiple vcxsrv instances.

**Comment by mviereck** [comment] 2019-05-09 12:29
Thanks for reporting!

It seems that x11docker somehow does not recognice X display numbers that are already in use. I successfully runs the first X server on display `:100`, but fails to run  second one on `:100`. It should run the second X server with display number `:101`.

I'll have a look why the display number check fails.

Meanwhile it should work if you manually specify a different display number with `--display 101`.

**Comment by 1138-4EB** [comment] 2019-05-09 12:35
> Meanwhile it should work if you manually specify a different display number with `--display 101`.

It works. I'm using this now to run the checks.

**Comment by mviereck** [comment] 2019-05-09 19:31
Ok, this one is fixed in latest commit. I did some test runs in a Windows VM, `--xwin` in Cygwin was affected, too.

**Comment by 1138-4EB** [comment] 2019-05-09 21:33
I can confirm that it works now.

**Comment by 1138-4EB** [comment] 2019-05-17 19:01
I think I'm having this problem in Cygwin:

![xwin_err](https://user-images.githubusercontent.com/6628437/57949983-36e06e80-78e6-11e9-8360-2b88d9541f21.png)

[XWin.100.log](https://github.com/mviereck/x11docker/files/3192729/XWin.100.log)
[x11docker.log](https://github.com/mviereck/x11docker/files/3192725/x11docker.log)

Note that there is no other Xwin server running, but there is an VcXsrv running at `100`.

I can work around this issue with ` ./x11docker --clipboard --no-auth --display 101 x11docker/check`.

**Comment by mviereck** [comment] 2019-05-17 19:15
> Note that there is no other Xwin server running, but there is an VcXsrv running at 100.

I did a test run yet with this setup, and it works. 
Maybe you forgot to run `x11docker --update-master` in Cygwin?

**Comment by 1138-4EB** [comment] 2019-05-17 19:18
> I did a test run yet with this setup, and it works.
> Maybe you forgot to run `x11docker --update-master` in Cygwin?

x11docker is not 'installed', I clone/pull the git repo and execute the script from there. Note that the command I used is `./x11docker --clipboard --no-auth x11docker/check`.

**Comment by mviereck** [comment] 2019-05-17 20:05
I cannot reproduce the issue, works ok here. `xauth` (#145) works, too.
My Windows installation just had an update, and my VcXsrv version is the same (1.20.1.4).
I have no more idea what might be different on your machine except a different x11docker version.

**Comment by 1138-4EB** [comment] 2019-05-17 20:09
I'm using the latest `master`. Might it be related to the fact that Cygwin is not installed in `C:` here?

**Comment by mviereck** [comment] 2019-05-19 10:59
> Might it be related to the fact that Cygwin is not installed in C: here?

I'll look into that, but it is quite unlikely. If started within Cygwin, x11docker checks `cygpath` to find the location of Cygwin.

> I'm using the latest master. 

Could you please try an older version? `v5.6.0` should have worked previously.

**Comment by 1138-4EB** [comment] 2019-05-19 21:41
> Could you please try an older version? `v5.6.0` should have worked previously.

I tried with `v5.6.0`, `v5.5.2`, `v5.5.0` and `v5.4.0`. All of them produce the same result/error. All of them work with `--display 101`.

**Comment by mviereck** [comment] 2019-05-19 22:14
Thank you.
It seems the check with `xwininfo.exe` somehow fails on your system.
The code Line is https://github.com/mviereck/x11docker/blob/master/x11docker#L2194
```
        --vcxsrv|--xwin) grep -q -E 'Authorization|Absolute' <<< "$(xwininfo.exe -display $Hostip:$Newdisplaynumber -root 2>&1)" || break ;;
```
Of interest is
```
xwininfo.exe -display $Hostip:$Newdisplaynumber -root 
```
Can you show me `command -v xwininfo.exe`?
In Cygwin it should be `/usr/bin/xwininfo.exe`.

In MSYS2 this probably fails, but this should work:
```
command -v /c/Program\ Files/VcXsrv/xwininfo.exe
```
Maybe you can also run a check with `xwininfo.exe` with correct IP and display number.

**Comment by 1138-4EB** [comment] 2019-05-19 22:34
> It seems the check with `xwininfo.exe` somehow fails on your system.

This was it. `xwininfo.exe` was installed/available in `/c/Program\ Files/VcXsrv/xwininfo.exe` but not in Cygwin. I installed it explicitly, and everything works as expected now.

Moreover, the authorization issue commented in [#145](https://github.com/mviereck/x11docker/issues/145#issuecomment-493296114) does not apply to cygwin (either with xwin or vcxsrv). It is still present with MSYS, tho.

**Comment by mviereck** [comment] 2019-05-20 06:38
> This was it. xwininfo.exe was installed/available in /c/Program\ Files/VcXsrv/xwininfo.exe but not in Cygwin.

Oh, ok. I thought it would be part of the `xinit` package. I'll add a dependency note in the wiki and a check for its availability in x11docker.

> authorisation issue

Does `/c/Program\ Files/VcXsrv/xauth.exe` exist?
It should be distributed with VcXsrv.

**Comment by 1138-4EB** [comment] 2019-05-20 11:04
> Oh, ok. I thought it would be part of the `xinit` package. I'll add a dependency note in the wiki and a check for its availability in x11docker.

Great!

> > authorisation issue
> 
> Does `/c/Program\ Files/VcXsrv/xauth.exe` exist?
> It should be distributed with VcXsrv.

Yes, it does exist. The following executables are available in `/c/Program\ Files/VcXsrv/`: plink, vcxsrv, xauth, xcalc, xclock, xhost, xkbcomp, xlaunch, xrdb and  xwininfo.

**Comment by mviereck** [comment] 2019-05-21 18:11
Closing this one, the origin issue is resolved.

Re: xauth / Authorization issue
@1138-4EB  Please let's discuss that in #160

**Closed by mviereck** 2019-05-21 18:11 UTC
Labels: bug
