### ISSUE TITLE
[Error] x11docker report error of no docker binary even when --install

### ISSUE THREAD

**Issue by CicadaSeventeen** [mviereck/x11docker#470] opened 2022-10-17 04:20 UTC
`x11docker --install` tells me docker backend not found.
I do not have `docker` but only `podman`. However, I do not think installing needs to detect which backend to use. To detect `Installermode` should be move to the front of `check_backend`.

BTW, I remember that old version of x11docker can fall back to `podman` if only `podman` is installed. Why this feature is abandoned?

**Comment by CicadaSeventeen** [comment] 2022-10-17 04:31
I have been revising the codes. Only thing needed here is to make `check_backend` lower. I am also trying to introduce a flag to disable `Installermode`. However,  codes of  `check_backend` is hard for me to understand why cannot fallback to `podman`.

BTW, you are expert in bash. It takes me some time to understand half of the codes of `x11docker` and it is incredible for me.

**Comment by CicadaSeventeen** [comment] 2022-10-18 12:26
I have solved the problem of `--install` . but I will not check for the backend fallback because I am afraid to destroy your bash. It is so delicate .

**Comment by mviereck** [comment] 2022-10-19 08:45
Thank you! I'll look closer at this.

**Comment by mviereck** [comment] 2023-01-16 13:12
The issue is fixed now.

**Closed by mviereck** 2023-01-16 13:12 UTC
Labels: bug

**Comment by CicadaSeventeen** [comment] 2023-03-08 05:38
> The issue is fixed now.

Not really. Now if I use `x11docker` 7.60 in system with `podman` only, it still can not detect `podman` and will try using `backend=docker` and then failed. I still have to manually add `backend=podman`
