### ISSUE TITLE
Headless Nvidia GPU and ffmpeg xsession recording

### ISSUE THREAD

**Issue by sxiii** [mviereck/x11docker#199] opened 2019-11-24 18:51 UTC
Hi @mviereck!

Thanks for helping me with the setup of x11docker --xvfb & ssh option; now going to (a little bit another) point.

My final goal is to run x11docker on Nvidia with GPU acceleration and record its accelerated performance via ffmpeg and 60 FPS. That's right; I don't even have to tunnel it anywhere. Just local recording!

Here's what I am doing:
```
read Xenv < <(x11docker --xvfb --hostnet --display=30 --runtime=nvidia --showenv -- jess/chromium --no-sandbox --autoplay-policy=no-user-gesture-required --kiosk "http://snap.menu/player.html?location_id=b4ec24fb-8425-444f-8eb4-33c8a2198798&device_id=965d2d2a-a1e8-4969-9ed7-fddaa1d22a0e")
```
Next, so that my server finds the display, I run:
```
echo $Xenv && export $Xenv
```
Finally, I am trying to capture the x11docker xserver with:
```
sudo ffmpeg -f x11grab -framerate 60 -y -t 00:00:10 -i :30 remote-host.mp4
```
And here's what it shows:
```
ffmpeg version 4.2.1-static https://johnvansickle.com/ffmpeg/  Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 6.3.0 (Debian 6.3.0-18+deb9u1) 20170516
  configuration: --enable-gpl --enable-version3 --enable-static --disable-debug --disable-ffplay --disable-indev=sndio --disable-outdev=sndio --cc=gcc-6 --enable-fontconfig --enable-frei0r --enable-gnutls --enable-gmp --enable-libgme --enable-gray --enable-libaom --enable-libfribidi --enable-libass --enable-libvmaf --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librubberband --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libvorbis --enable-libopus --enable-libtheora --enable-libvidstab --enable-libvo-amrwbenc --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libdav1d --enable-libxvid --enable-libzvbi --enable-libzimg
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
[x11grab @ 0x6e4c880] XFixes not available, cannot draw the mouse.
```
And than it hangs forever (although it should stop recording in 10 seconds because of -t flag), until I press Ctrl+C, and it does not transcode anything (here's output):
```
Input #0, x11grab, from ':30':
  Duration: N/A, bitrate: N/A
    Stream #0:0: Video: rawvideo (BGR[0] / 0x524742), bgr0, 640x480, 60 fps, 1000k tbr, 1000k tbn, 1000k tbc
Stream mapping:
  Stream #0:0 -> #0:0 (rawvideo (native) -> h264 (libx264))
Press [q] to stop, [?] for help
Finishing stream 0:0 without any data written to it.
[libx264 @ 0x6e56b40] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2 AVX512
[libx264 @ 0x6e56b40] profile High 4:4:4 Predictive, level 3.1, 4:4:4, 8-bit
[libx264 @ 0x6e56b40] 264 - core 157 r2969 d4099dd - H.264/MPEG-4 AVC codec - Copyleft 2003-2019 - http://www.videolan.org/x264.html - options: cabac=1 ref=3 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=4 threads=6 lookahead_threads=1 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=2 keyint=250 keyint_min=25 scenecut=40 intra_refresh=0 rc_lookahead=40 rc=crf mbtree=1 crf=23.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
Output #0, mp4, to 'remote-host.mp4':
  Metadata:
    encoder         : Lavf58.29.100
    Stream #0:0: Video: h264 (libx264) (avc1 / 0x31637661), yuv444p, 640x480, q=-1--1, 60 fps, 15360 tbn, 60 tbc
    Metadata:
      encoder         : Lavc58.54.100 libx264
    Side data:
      cpb: bitrate max/min/avg: 0/0/0 buffer size: 0 vbv_delay: -1
frame=    0 fps=0.0 q=0.0 Lsize=       0kB time=00:00:00.00 bitrate=N/A speed=   0x    
video:0kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
Exiting normally, received signal 2.
```

So here are few questions:
* Do you know why there is no ffmpeg video output? It might be a permission issue? I've tried running ffmpeg both as normal user and as root, nothing changes.
* Should I try to run something like ```xhost +local:root;``` inside of the x11docker container or it won't help?
* Probably --xvfb is not working with GPU acceleration? So even if I will be able to capture the video from Xserver, it will be without acceleration?

That's it. Thank you very much again :)

**Comment by mviereck** [comment] 2019-11-24 19:24
> Do you know why there is no ffmpeg video output? 

I don't know. I can reproduce the issue, tested with `--xvfb` and `--xephyr`. If I record the host display `:0`, ffmpeg works.

> It might be a permission issue?

No. Just in case I've added `--no-auth` to disable X cookie authentication, but that didn't help.

> Should I try to run something like xhost +local:root; inside of the x11docker container or it won't help?

`--no-auth`  is equal to `xhost +` for everyone.

> Probably --xvfb is not working with GPU acceleration? So even if I will be able to capture the video from Xserver, it will be without acceleration?

Yes, Xvfb only supports software rendering.

I'll investigate, I don't have an idea yet why ffmpeg does not work with x11docker's X server setup.

**Comment by sxiii** [comment] 2019-11-24 19:29
Great, thanks for looking into that. But as for now; maybe you know which software works well for screen recording with x11docker Xserver? Like, recordMyDesktop or any other tool? Maybe it's ffmpeg bug anyways.

**Comment by mviereck** [comment] 2019-11-24 19:37
> But as for now; maybe you know which software works well for screen recording with x11docker Xserver? 

Sorry, I don't know. Did not need that ever myself.
There is an `xpra screenshot` command that may help partially.

**Comment by sxiii** [comment] 2019-11-24 19:49
Ok got it. So currently the solution to this can be to record session through Xpra, VNC or xvfb? But with VNC it will be without acceleration so...

**Comment by mviereck** [comment] 2019-11-24 20:12
I found a solution!

x11docker disables X extension MIT-SHM. It serves to share memory with applications. But that fails with isolated containers.

With x11docker option `--hostipc` the container shares memory with the host and x11docker allows MIT-SHM.

Use `--hostipc` and ffmpeg works.

**Comment by sxiii** [comment] 2019-11-24 20:53
Wow cool! That was really fast! :) Thanks.

So lastly, I wonder what are my steps in getting fully-fledged Nvidia acceleration for chrome...

Probably the best way would be build them alltogether based on nvidia system image. What do you think?

**Comment by mviereck** [comment] 2019-11-24 21:01
At first we need a working `--xorg` setup.
As seen in #197 you currently get a "No screens found" error.

Because you cannot physically provide a (fake) monitor at the server, you need to configure `xorg.conf` to allow a virtual display.

I found this thread that gives some first hints: https://devtalk.nvidia.com/default/topic/585014/how-to-configure-x-server-to-work-headless-as-well-with-any-monitor-connected-/

You'll need to do some tests and investigation yourself because the setup depends on the GPU hardware. You are probably able to get at least a virtual 640x480 monitor with the hints of the thread. That would be a first step.

**Comment by sxiii** [comment] 2019-11-24 21:08
Interestingly, the session recorded with FFMPEG@60fps looks running smoothly while being ``x11docker --xvfb --display=30 --showenv --size=1280x1024 --hostipc`` -> can that be possible?

I will also look further into configuring a fake monitor. Thanks for the links.

**Comment by sxiii** [comment] 2019-11-24 22:00
When I make it smaller (ex. 800x600) then everything seems to be in place; but chome still starts not in fullscreen mode even I passed "--kiosk" to chrome and "-f" to x11docker. 
![image](https://user-images.githubusercontent.com/575925/69502311-27ce1f00-0f0e-11ea-9828-6f6b505d78f2.png)

**Comment by sxiii** [comment] 2019-11-25 04:20
Moved to Ubuntu 18.04 server (from amazon linux) to test out Docker 19.03... Hope it might help...

**Comment by mviereck** [comment] 2019-11-25 07:05
> Interestingly, the session recorded with FFMPEG@60fps looks running smoothly while being x11docker --xvfb --display=30 --showenv --size=1280x1024 --hostipc -> can that be possible?

Yes. The speed /fps of software rendering depends on the CPU and on the requested amount of calculation. It can be much faster than 60fps or much slower.

> sudo nvidia-xconfig --allow-empty-initial-configuration
It seems it's created /etc/X11/xorg.conf file with correct options. 
> And the --xorg option is also not working. Both not finding screens.

Could you show me the generated `xorg.conf`? Though, if everything looks right but fails, you should ask at NVIDIA and/or amazon. 
To exclude issues caused by x11docker, test with `sudo xinit -- :10`

> When I make it smaller (ex. 800x600) then everything seems to be in place; but chome still starts not in fullscreen mode 

Maybe `chrome` needs a window manager to run fullscreen. Install e.g. `xfwm4` and try option `--wm=xfwm4`. (x11docker should autodetect this, should even work without setting this option).

**Comment by sxiii** [comment] 2019-11-25 08:53
Oh I tried a lot today! Here's what I've done:

* Moving to Ubuntu 18.04
* Installing everything once again (all the stuff: docker, nvidia driver, cuda, nvidia-docker, x11docker...)
* Writing own Dockerfile based on yours from the sample in wiki here (nvidia one)
* Adding repos and matchbox window manager to docker image (I thought it will help chrome; but it didn't)
* Synchronized drivers on the host server (440.36) and client docker (440.36)
* Put the drivers in the folder

So I could know for sure that everything works. Now, what's in a way unclear for me, is what are the flags for my container if I build it based on x11docker nvidia image which was based on nvidia image? Should I add anything at all?

So far what I've tried:
* Single --xvfb works as earlier. After recording screen with ffmpeg it seems that speed is much higher, but the image still lags in some points (which shouldn't happen with Nvidia Tesla T4 video cards ?)
* Adding --gpu; --runtime=nvidia or --xorg crushes the container with a EE error message from Nvidia driver stating that there are no Xserver (which is right; but...)

What can I try from this moment? Is there a way I know for sure that there's acceleration? Is that okay to record ffmpeg from server inside docker (so we are having here host->guest overhead) or maybe I should add ffmpeg inside docker container and write the session from there?

**Comment by mviereck** [comment] 2019-11-25 09:13
> Adding repos and matchbox window manager to docker image (I thought it will help chrome; but it didn't)

I mean a window anager on host. If you have it in the image, you need to start it youself in the container.
Alternatively you can pull image `x11docker/openbox`. See `x11docker --help` for option `--wm`.

> Now, what's in a way unclear for me, is what are the flags for my container if I build it based on x11docker nvidia image which was based on nvidia image?

If your image is based on one on nvidia-docker, you need `--gpu --runtime=nvidia`. 
If you have installed the driver itself in the image, you need `--gpu`. 
If you provide the driver installer to x11docker, you need `--gpu`.

> Like --gpu or --runtime=nvidia or --xorg?

NVIDIA only supports `--hostdisplay` and `--xorg`.

> But the recording stil shows some lags. What can I try from this moment?

Try to succeed with `sudo xinit -- :10`. As long as this fails, you won't get GPU acceleration.

**Comment by sxiii** [comment] 2019-11-25 09:27
Oh I've managed to run it with --gpu! But it's still lagging a bit.

I am thinking I should try:
* Run ffmpeg recording from separate container
* Run ffmpeg from the same container
* Install another window manager instead of "matchbox" that's not helping anyways.

Here's what happens when I run xinit:
```
sudo xinit -- :10


X.Org X Server 1.19.6
Release Date: 2017-12-20
X Protocol Version 11, Revision 0
Build Operating System: Linux 4.4.0-148-generic x86_64 Ubuntu
Current Operating System: Linux ip-172-30-1-168 4.15.0-1054-aws #56-Ubuntu SMP Thu Nov 7 16:15:59 UTC 2019 x86_64
Kernel command line: BOOT_IMAGE=/boot/vmlinuz-4.15.0-1054-aws root=UUID=c530eaa8-71ad-4d2e-8870-a15b5f24e30e ro console=tty1 console=ttyS0 nvme_core.io_timeout=4294967295
Build Date: 03 June 2019  08:10:35AM
xorg-server 2:1.19.6-1ubuntu4.3 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.34.0
	Before reporting problems, check http://wiki.x.org
	to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
	(++) from command line, (!!) notice, (II) informational,
	(WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(==) Log file: "/var/log/Xorg.10.log", Time: Mon Nov 25 09:27:14 2019
(==) Using config file: "/etc/X11/xorg.conf"
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
xinit: Unable to run program "xterm": No such file or directory
Specify a program on the command line or make sure that /usr/bin
is in your path.

xinit: connection to X server lost

waiting for X server to shut down (II) Server terminated successfully (0). Closing log file.
```

**Comment by sxiii** [comment] 2019-11-25 09:39
I think everything works now! It recorded a file that's 100 mb (per minute) instead of 2-3 mb (per minute) and this one seems nearly perfect! Now I only have issues with Chrome window size and that's all! I will now experiment with --wm options!

Thanks @mviereck you are a magician for real! Do you have patreon page or something? (:::

**Comment by sxiii** [comment] 2019-11-25 09:43
Can I combine ```FROM x11docker/nvidia-base``` and ```FROM x11docker/openbox``` somehow or only manually joining dockerfiles?

**Comment by mviereck** [comment] 2019-11-25 11:34
> Can I combine FROM x11docker/nvidia-base and FROM x11docker/openbox somehow or only manually joining dockerfiles?

x11docker combines them itself. It runs your container and the openbox container on the same X server.

> I think everything works now! It recorded a file that's 100 mb (per minute) instead of 2-3 mb (per minute) and this one seems nearly perfect! 

Rather check with `x11docker --gpu --xorg x11docker/check` if you have provided the `.run` installer file. I would not give a bet on file size data.

> Thanks @mviereck you are a magician for real! 

You are welchome! :-)

> Do you have patreon page or something? (:::

It's all for free  ...

**Comment by sxiii** [comment] 2019-11-25 18:09
> x11docker combines them itself. It runs your container and the openbox container on the same X server.

Ahh, cool. So ```--wm=x11docker/openbox``` should do the trick?

> Rather check with `x11docker --gpu --xorg x11docker/check` if you have provided the `.run` installer file. I would not give a bet on file size data.

The things is that not only video size grew; but also the video is now not lagging (**only a littlle in one place**); and the resource usage of CPU dropped dramatically (according to Amazon graphs). So; I bet it's working on the GPU. Also it was 2-5 mbps bitrate when converting with CPU, now it's 20-60 mbps. So I'm pretty sure GPU is working well. 

How do you think, is there might be overhead because ffmpeg is running on the server while Xserver is inside the container? Anyways; I'd better also check that out.

A lot of success; but also maybe I found a weird (maybe? bug related to window manager. I'll open a new issue for that.

> It's all for free ...
You're very generous man. Your help is highly appreciated by at least two of us :) Your software is the way it should always be in the opensource world! Thanks again! :)

**Comment by mviereck** [comment] 2019-11-25 20:27
>  the resource usage of CPU dropped dramatically (according to Amazon graphs). So; I bet it's working on the GPU

ok, low CPU usage is a good indicator.

> How do you think, is there might be overhead because ffmpeg is running on the server while Xserver is inside the container? 

No, that should cause no overhead.
For clarification: The X server runs on the host, not in container. Both chrome and ffmpeg communicate with it. 

> You're very generous man. Your help is highly appreciated by at least two of us :) Your software is the way it should always be in the opensource world! Thanks again! :)

:)
I also get a lot of free software and free help in the open source world. I am happy to give a bit, too.
The x11docker project is a hobby in free time, and I like it to be free of money and other constraints of my regular (non IT) work.

**Comment by mviereck** [comment] 2019-11-27 18:59
It seems everything is solved so far, closing this ticket now.
Feel free to open new tickets if something comes up.

**Closed by mviereck** 2019-11-27 18:59 UTC
Labels: question

**Comment by mviereck** [comment] 2019-11-28 09:52
I just found this repository: https://github.com/ryought/glx-docker-headless-gpu

It's written in japanese and I can read only a few english words. But it sounds quite interesting and targets headless NVIDIA GPU, too.

Picking one interesting part:
```
nvidia-xconfig \
  -a \
  --virtual=1280x1024 \  # 仮想スクリーンの解像度
  --allow-empty-initial-configuration \ # ディスプレイがなくてもXサーバーを起動する
  --enable-all-gpus \  # GPUを有効化
  --busid PCI:0:4:0  # GPUを見つけられるようにBUSIDを指定しておく
```

**Comment by sxiii** [comment] 2019-11-28 21:53
@mviereck so that will allow us to create fake Xorg dummy server with any size we like on specific GPU by utilizing it's PCI bus id? That would be great!

**Comment by mviereck** [comment] 2019-11-28 22:10
We already got it to work without Xdummy+VirtualGL+VNC. That would add complexity that is probably not needed.

In the cited `nvidia-xconfig` command I found of interest:
 - `--virtual=1280x1024` to specify the monitor size
 - `--busid PCI:0:4:0 ` to specify desired GPU

The repository may provide further interesting setups and possibilities. @ryought seems to have done a lot of investigation.

**Comment by sxiii** [comment] 2019-11-29 17:39
Yeah I've got like 1920x1080 which's okay for me :) But that's useful especially with busid's.

**Comment by richardabear** [comment] 2023-09-21 10:45
Hi @sxiii I sent you an email, hoping to connect regarding this issue
