### ISSUE TITLE
Specifying SHELL to be "bash" as an "--env" argument seems to prevent C-z (suspend) handling in the terminal

### ISSUE THREAD

**Issue by Intensity** [mviereck/x11docker#457] opened 2022-07-13 21:52 UTC
I had been adding `--env SHELL=/bin/bash` to the `x11docker` invocation and then I noticed that most interactive commands in the terminal are not responding to suspend (Control-Z), and so that means when I run `sleep 100` then type Control-Z then there is no effect. Control-C however works. I checked `stty -a` and this shows normal settings for `susp`. I even built completely minimal Alpine and Devuan images that only add `stterm` and `bash` and these problems only seem to show themselves when `SHELL` is set to `bash`. I tried not including the `--env` to begin with, setting it to `zsh`, setting it to `dash` and those all worked fine.

Then I tried running `SHELL=/bin/bash st` within the invoked `x11docker` container (with `--env SHELL=/bin/bash`) and interactive suspend didn't work. I then ran `SHELL=/bin/dash st` and in the subsequent spawned window ran `SHELL=/bin/bash st` and in those final two windows (even in the very final one in which `SHELL` is bash), suspend _did_ work. Of course I could try a lot of strange permutations to attempt to hone in on what works and what doesn't, but because `stty -a` output looks as though `susp` is assigned to Control-Z just as always, I don't really know what the root cause is when this is manifesting. `xev` would just show correctly processed keypresses, and I would ordinarily turn to `stty -a` as the source of truth. Without involving `x11docker`, a command like `SHELL=/bin/bash st` works without an issue.

A command that has its own "handler" for Control-Z (like `less` I believe) will at least _process_ a suspend request but that may only come up because of custom code for that command; in general the signal doesn't seem to be getting passed in the shell, specifically when there are conditions that look like `SHELL` being `bash` at invocation of `x11docker`. I don't know if the suspend event is somehow making its way elsewhere, like to `init`, or if it's being masked, or if some setup scripts are doing different things conditionally if the shell is bash. Pressing a Control-V Control-Z sequence reveals "^Z" is added in the working command line, so it's not as though Control-Z isn't being seen.

I'm mentioning this here because it seems pretty confusing and anomalous and maybe something can be addressed that could help prevent further unexpected issues. In my case I'm using `--nxagent` (and also a non `--desktop` mode with just `st` as a command), although I'm hoping this is easily reproducible, especially since my containers were built so minimally from the base images and also because I tried a variety of permutations.

**Comment by mviereck** [comment] 2022-07-14 08:32
Thank you for the report!
Yet I cannot reproduce the issue.
I've tested with debian+xterm and alpine+st, using `--nxagent` or `--xpra`.
```
FROM alpine
RUN apk add --no-cache bash st font-liberation-mono-nerd
```
Note that x11docker automatically sets `SHELL=/bin/bash` if `bash` is installed in the image. (It also makes an entry in `/etc/passwd`.) Otherwise it sets `/bin/sh`. You can adjust that with option `--shell=SHELL`.

Maybe your host intercepts the key? Which desktop do you use?

**Comment by Intensity** [comment] 2022-07-14 20:37
That's even stranger that you're not able to reproduce it.

For _x11docker_ to behave differently for me whether I specify `--env SHELL=/bin/bash` or not suggests that there's something happening that's conditional on that.

I'm using _Devuan_ as a host, and `podman` (rootless) as a backend.

Also I tried with `7.1.3` and `7.3.3-beta1` versions of x11docker and I get the same result.

The host can't be intercepting the key (in general) because there are many cases in which the problem doesn't manifest.

I happen to be using _spectrwm_ as a window manager.

It doesn't make a difference where the mouse cursor is.

My intuition suggests something about signal handling. Maybe the "init" being run in the container, on the podman backend, is somehow "absorbing", trapping, or masking that signal. The signal might ordinarily go to a process or a process tree/parent and somehow that might be working differently depending on these strange conditions. Maybe the init process in the container accepts the signal and then drops it, much like a no-op.

If you were to test using `podman` (rootless mode) with `crun`, you may be able to reproduce this. I'm also using cgroup manager of _cgroupfs_ and I add `--events-backend file` to the _podman_ invocation. Although I'm guessing a change to rootless `podman` and `crun` in your testing may be sufficient to reproduce.

**Comment by mviereck** [comment] 2022-07-14 20:53
I doubt that the init process is involved.
Most likely the issue is somehow related to X11. After all, the signal is just a key press, and key presses are job of the X server communicating with the X client.

It is worth to try another X server, e.g. `--xephyr` instead of `--nxagent`.
If that makes no difference, I'd suspect spectrwm.

I've tried to reproduce with rootless podman, alpine+st, --nxagent, but still no issue.

Wich version of nxagent do you have?
```
$ apt search nxagent
nxagent/stable,now 2:3.5.99.26-2 amd64  [installiert]
```

> For x11docker to behave differently for me whether I specify --env SHELL=/bin/bash or not suggests that there's something happening that's conditional on that.

Are you sure that `--env SHELL=/bin/bash` is a condition?
Please check `echo $SHELL` in your container without setting `--env SHELL=/bin/bash`.

**Comment by Intensity** [comment] 2022-07-14 22:29
Hi,

I've honed in on what seems most essential to reproduce. Sorry that I didn't provide that earlier; I was banking on it being easier to surface the problem. Anyhow it appears that `--no-setup` is important in order to reproduce the problem. I gather that this option isn't probably recommended and is meant to be a DIY theme, but anyhow since what I experienced is pretty anomalous I want to make sure that the problem doesn't make its way elsewhere. It may be interesting to determine the underlying issue.

For environment, I pruned almost all of my host environment variables before proceeding, just to be sure to rule out something unexpected. That left me with:
```
  DISPLAY=:0
  HOME=/home/myusername
  LANG=C
  LOGNAME=myusername
  PATH=/sbin:/bin:/usr/sbin:/usr/bin
  PWD=/home/myusername
  SHELL=/bin/bash
  TERM=vt220
  USER=myusername
```
Also, for image construction, in the image Dockerfile, on top of `docker://debian:bullseye-slim` I add these packages: `stterm bash procps`

And then, perhaps nonstandard for me (but might not have an impact on reproducibility), I happen to have a wrapper around podman to better support rootless operation. This appears earlier in my `PATH`. Anyhow it looks like this:
```
  export XDG_RUNTIME_DIR=/run/myusername/1000
  exec /usr/bin/podman --runtime crun --storage-driver vfs --cgroup-manager cgroupfs --events-backend file "$@"
```
What follows now are a set of example runs I make and the results that I get
```
x11docker --no-setup --backend=podman --nxagent -- -- ${IMAGE} st

- Shell suspend works (expected)
- Reported $SHELL is /bin/sh (not expected, since calling environment already had SHELL set to /bin/bash and it is exported)
- /bin/sh is what appears in /etc/passwd in the container for the user shell (not expected, although on the other hand since --no-setup is meant to be DIY, it may be the normal path)
- Process tree is /dev/init -- st :: st :: /bin/sh (not expected, since I would expect /bin/bash to be used)
- I get the additional x11docker Error: no container with name or ID x11docker_... found: no such container (might be benign; anyhow it doesn't prevent me from using the container)

x11docker --shell=/bin/bash --no-setup --backend=podman --nxagent -- -- ${IMAGE} st

- Shell suspend works (expected)
- Reported $SHELL is /bin/sh still (not expected, given the command line argument I gave)
- /bin/sh is what appears in /etc/passwd in the container for the user shell (not expected because of the argument, unless --no-setup makes minimal changes to the file, in which case it may be normal for such quirks)
- Process tree is /dev/init -- st :: st :: /bin/sh (unexpected, since I specified --shell)
- I get the additional x11docker error as mentioned

x11docker --env SHELL=/bin/bash --no-setup --backend=podman --nxagent -- -- ${IMAGE} st

- Shell suspend does not work (not expected; it's a mystery as to what's really going on)
- Reported $SHELL is /bin/bash (expected, although I wonder why the above two runs don't propagate that)
- /bin/sh is what appears in /etc/passwd in the container for the user shell (seems to be a persistent result, and so I gather it's more likely to be due to the use of --no-setup)
- Process tree is /dev/init -- st :: st :: /bin/bash (expected - finally shows the SHELL I provided)
- I get the additional x11docker error as mentioned

x11docker --env SHELL=/bin/bash --backend=podman --nxagent -- -- ${IMAGE} st

- Shell suspend works (expected)
- Reported $SHELL is /bin/bash (expected)
- /bin/bash is what appears in /etc/passwd in the container for the user shell (expected; perhaps the lack of --no-setup allows for normal modifications and processing)
- Process tree is /usr/local/bin/init -- /bin/sh - /x11docker/containerrc :: sh /x11docker/cmdrc :: st :: /bin/bash (plus some tail commands) (an alternative tree compared to before that is more fully fledged so to speak; I didn't try variations to enforce a particular init system)
- I don't get that x11docker error/warning message I mentioned

x11docker --env SHELL=/bin/bash --backend=podman --nxagent -- --read-only -- ${IMAGE} st

- Shell suspend works (expected)
- Reported $SHELL is /bin/bash (expected)
- /bin/sh is what appears in /etc/passwd in the container for the user shell (somewhat expected; here it's clearly inhibited due to my use of --read-only but without --no-setup : that is, not following guidelines)
- Process tree is /usr/local/bin/init -- /bin/sh - /x11docker/containerrc :: sh /x11docker/cmdrc :: st :: /bin/bash (plus some tail commands)
- I don't get the x11docker error/warning mentioned earlier but I got other things that might be expected, like inability to change /etc/shadow, but these are likely to be expected given that I didn't also include --no-setup
```
Anything that sets _$SHELL_ to something other than bash (like dash or sh) also seems to allow shell suspending to work fine. However for the third case to be distinct from the first two is confusing to me.

Hopefully that should at least help with reproducibility. When there is an inability to suspend processes, I wonder if signal handling is working differently, like operating on a process group, but I don't really know. The version of _nxagent_ on the host is `2:3.5.99.26-2`. I'm wondering if you were running `crun` or `runc`. Also I get the same result with `--xephyr`.

**Comment by Intensity** [comment] 2022-07-15 23:02
Thanks for the update. Although I wouldn't know why the `/etc/passwd` entry would have that result for the terminal, I also wonder about the other tests I ran initially in which I spawned another `st` from the existing `st` (with different `SHELL` settings I set manually). Since I believe `st` allocates a whole new `pts`, I would guess that it wouldn't inherit any (quirky) stty settings (though, that confusingly doesn't seem to be the problem at least due to `stty -a` output). But `/etc/passwd` remains constant, and yet one further spawn works and another does not.

While I don't know if this boils down to a bug or anomaly in `st` or `bash`, the confusing part is that this creates some deviation from what's expected or guaranteed by typical `stty` settings in UNIX (something I would only expect by user error, like the same key bound to more than one signal and then only one signal could result in the end). And my "Control-V Control-Z" result confirms that the Control-Z event is making its way into the session just fine. And so this leads me to consider that it's something about quirky or misrepresented `stty` settings or somehow the signal is being masked or passed to another level (unmasked).

Well I'm keeping my above analysis even though I've since run a new test, which is testing the result of `kill -TSTP` (and for contrast `-STOP`) on a process started with `sleep 100 &`. The terminal suspend is nonresponsive if and only if `kill -TSTP` has no effect (which actually also shouldn't be the case; `TSTP` should stop the process from the shell's perspective and await the user to either move it to the foreground or continue this in the background). In all cases `-STOP` has an effect; perhaps the processes' signal handling isn't altered or can't be altered with respect to that signal.

Note that I also confirmed a case in which the original `st` was not working (in the `-TSTP` sense) and then I spawned a new `st` just by changing `SHELL` (and not `/etc/passwd`) and then in that subsequent shell, `kill -TSTP` _did_ have an effect.

I don't believe processes typically "know" (except by some complicated reverse engineering or system-wide tracing) where a given signal "came from", so there seems to be something tainted with the environment that starts up those processes. To me it looks like an incorrect masking or unmasking of signal handling (maybe with respect to process groups or hierarchies), but that's a guess without knowing any real internals.

Maybe the init process in the container attempts to create some kind of safety that the first spawned process won't be accidentally suspended by the user; if it's at all even possible, maybe it quickly revives a process that was suspended in that way before the shell notices. Perhaps a different `init` could have a different result...

**Comment by mviereck** [comment] 2022-07-16 11:33
> Perhaps a different init could have a different result...

Indeed, this makes a difference!
By default x11docker runs with a small init system. In case of `--no-setup` it just sets option `--init`. In case of docker this is `tini` on most distributions, shipped as `/usr/bin/docker-init`. I am not sure yet what is used by podman.

If I disable this with x11docker option `--init=none`, suspend works in cases where it failed above!

**Comment by mviereck** [comment] 2022-07-16 13:34
So the issue appears only in combination of `--no-setup --backend=podman` due to suspicious behaviour of `podman run --init`. Setup of `/etc/passwd` is likely unrelated.
For this case x11docker automatically sets `--init=none` now and prints:
```
x11docker note: Option --no-setup --backend=podman: Running with --init=none
  to allow regular terminal emulator behaviour in container.
  Terminating x11docker with CTRL-C will fail.
```

Thank you very much for pointing on the init system! I'd never get that idea on myself.

**Comment by Intensity** [comment] 2022-07-17 06:23
Thanks. I'm still curious what the underlying issue is (for example, what it is about the chosen `init` system that is causing that particular outcome, as it may ultimately be signal related), but at least I'm not blocked now.

The last thing I'd wonder about here from the standpoint of _x11docker_ is what the disadvantages are to not run an `init`. Maybe it's that the continued life of a container is dependent upon PID 1 hanging around, and if for some reason a non-init PID 1 (such as `st` while used with `--init=none`) terminates, then the container may end its life early.

Although I believe there was something about reaping process children, or something like hanging around zombie processes when there isn't a proper `init` system I read / experienced before. Or there's protection from an accidental termination of the main process, by auto-reviving it. It's the category of process signal handling, or reaping of process children, that prompts me to want the right in-container setup. I don't know definitively the impact of not running a real or a minimal `init`, but I'm sure it's documented somewhere.

Perhaps if I find the importance of running _some_ `init`, I can then find whichever minimal `init` best meets my anticipated or minimal needs and then stick with it.

**Comment by mviereck** [comment] 2022-07-17 08:55
> Thanks. I'm still curious what the underlying issue is

I am curious, too. Especially since a terminal emulator is an X11 client, and I would not expect an init to intercept a keypress signal. If all would happen within a tty only, I could easier accept this fact.

> The last thing I'd wonder about here from the standpoint of x11docker is what the disadvantages are to not run an init.

At least one issue in practice: x11docker cannot be terminated by CTRL-C. Container init systems `tini` and `catatonit` can handle this.

> Maybe it's that the continued life of a container is dependent upon PID 1 hanging around, and if for some reason a non-init PID 1 (such as st while used with --init=none) terminates, then the container may end its life early.

A container runs as long as it has a PID 1.

> Although I believe there was something about reaping process children, or something like hanging around zombie processes when there isn't a proper init system I read / experienced before.

I've read this, too. I am not sure how important this really is, but just in case it is good to have an init that serves this issue.

> Or there's protection from an accidental termination of the main process, by auto-reviving it. 

Somewhat related: x11docker terminates if the desired command terminates. But some applications like e.g. `gnome-terminal` fork themself, and would cause x11docker to terminate because the pid is no longer in use. Option `--checkwindow` watches the window instead of the pid to fix this.

> It's the category of process signal handling, or reaping of process children, that prompts me to want the right in-container setup.

Proper signal forwarding seems the most important container init job to me. Zombie reaping is a nice bonus.

Without `--no-setup` x11docker shares `catatonit` or `tini` from host and runs it as PID 1. Otherwise it uses `--init` yet (now with exception of `--backend=podman`.)
I'll check how to implement this with `--no-setup`, too.

**Comment by mviereck** [comment] 2022-07-17 11:33
> Without --no-setup x11docker shares catatonit or tini from host and runs it as PID 1. Otherwise it uses --init yet (now with exception of --backend=podman.)
I'll check how to implement this with --no-setup, too.

I've implemented this now, x11docker shares `catatonit` or `docker-init` from host with `--no-setup` now and uses it as init in container. (You can check with `pstree`).

However, two odd issues remain if using `--backend=podman`: The terminal output of `--debug` or `--verbose` is messed up with broken newlines, and CTRL-C does not work.

**Comment by Intensity** [comment] 2022-07-17 16:19
Thanks for the update.

For the general case (without `--no-setup`), is there a practice to use the `init` binary from the container? That assumes that the user included it in the image, but that's also something that could be checked.

For `catatonit` it seems that there might be one relevant option (`-g`) to this original noted issue. And then for `tini` there is `-g` and a few more (depending also on whether it was compiled minimally), and some experiments with those options might help reveal what's most relevant to _x11docker_ usage.

On a slight tangent, I'm wondering if _x11docker_ usage in `--tty` mode is fairly common too, and if so, maybe it can be positioned as a best practices way to start a container using minimum functionality / maximum security by default according to whichever backend and host/container configuration is being used. As an _ad hoc_ example, here's how I have been running `podman` for one use case:

```
podman --runtime crun --storage-driver vfs --cgroup-manager cgroupfs --events-backend file run --pull never --rm --interactive --tty --quiet --name example --cpus 1 --label=name=example --hostname example --user 1000:1000 --userns=keep-id --group-add 1000 --network none --no-hosts --oom-kill-disable --cap-drop ALL --security-opt no-new-privileges --init --mount type=bind,source=/opt/example,target=/opt/example,readonly --tz US/Pacific --env TZ=US/Pacific --env TERM=vt220 --env TMP=/var/tmp --env TMPDIR=/var/tmp --env TEMP=/var/tmp --volume /opt/example2:/opt/example2:ro --read-only --detach-keys 'ctrl-^,ctrl-^' -- ${IMAGE_OR_ROOTFS} ${COMMAND}
```

It's pretty arbitrary and who knows - maybe I could even tighten the security further with another option - but that's quite a long command line to type up, and so I may prefer a wrapper. That can be opened in another thread/ticket.

**Comment by mviereck** [comment] 2022-07-18 08:39
> For the general case (without --no-setup), is there a practice to use the init binary from the container? That assumes that the user included it in the image, but that's also something that could be checked.

You can use `--init=none`. If the container runs it own init, it will become PID 1. This is independent from `--no-setup`.
There are some checks for init in container and they print messages including a hint for `--init=none` . However, it's up to the user to set this up right. And x11docker might not recognize every possible custom init setup in container.

> For catatonit it seems that there might be one relevant option (-g) to this original noted issue. And then for tini there is -g and a few more (depending also on whether it was compiled minimally), and some experiments with those options might help reveal what's most relevant to x11docker usage.

This option is interesting. I thought the `-g` behavior is already the default. i might add `-g` in x11docker, just in case.

> On a slight tangent, I'm wondering if x11docker usage in --tty mode is fairly common too, and if so, maybe it can be positioned as a best practices way to start a container using minimum functionality / maximum security by default according to whichever backend and host/container configuration is being used. 

I am not sure how many people use this. It appears in only few cases in tickets, mostly if `--interactive` is used as well.
At least one time someone reported that he uses x11docker with `--tty` just for the comfort to have a secured container including a valid unprivileged user setup.

> As an ad hoc example, here's how I have been running podman for one use case:
> That can be opened in another thread/ticket.

Yes, it makes sense to discuss this in  a new ticket. I appreciate it if we discuss this. The default x11docker setups include several of your option examples (compare shown command in `--debug`). The greatest impact for security has `--cap-drop ALL --security-opt no-new-privileges`. But likely there are ways to further improve container security.

**Comment by Intensity** [comment] 2022-07-18 12:00
For the time being I've been letting the command line I run within the _x11docker_ container to be an _init_ commandline itself. For example:

```
 /usr/bin/tini -v -v -w -g -- st
```

I find that this gives interesting verbose output for me too. By default I combine `--no-setup`, `--init=none`, and even `--env SHELL=/bin/bash` from the _x11docker_ side with the custom _podman_ options of: `--read-only` and `--rootfs` and these all work fine together. I actually have my own idempotent "setup script" so to speak that I run with the `-e` option for `st` (which helps work with the custom `HOME` location and the read-only property of the _rootfs_).

**Comment by mviereck** [comment] 2022-07-25 19:04
I'll close this ticket because the underlying issues are solved.

**Closed by mviereck** 2022-07-25 19:04 UTC
Labels: bug
