### ISSUE TITLE
pulseaudio after reboot

### ISSUE THREAD

**Issue by zwfcrazy** [mviereck/x11docker#439] opened 2022-05-12 03:57 UTC
Hi, I have an application that runs in a container that restarts after rebooting the whole system. However, the pulseaudio socket created in /tmp no longer works after rebooting. In addition, I don't want to login the computer after rebooting. I want everything to work just by pressing the power button on the computer. What should I do to make pulseaudio work in such a case?

I also tried to mount the user socket in /run/user/1000/pulse into container. This works before rebooting. However, after rebooting, the directory /run/user/1000/pulse became empty. I guess this problem relates to container mount binding, but not sure what happened exactly.

**Comment by mviereck** [comment] 2022-05-12 06:32
In general your setup should just work.
x11docker requests a new pulseaudio socket on every restart. However, maybe the pulseaudio server is not already running when you start x11docker? It should be started automatically after login (or auto-login), and x11docker must start afterwards.
If the issue is elsewhere, you could try `--pulseaudio=tcp` that does not use a socket but a TCP connection. (x11docker also needs option `--network` to allow TCP connections.)

**Comment by zwfcrazy** [comment] 2022-05-12 06:55
> 



> In general your setup should just work. x11docker requests a new pulseaudio socket on every restart. However, maybe the pulseaudio server is not already running when you start x11docker? It should be started automatically after login (or auto-login), and x11docker must start afterwards. If the issue is elsewhere, you could try `--pulseaudio=tcp` that does not use a socket but a TCP connection. (x11docker also needs option `--network` to allow TCP connections.)

I  think because docker has root privilege, a container restarts before user login and certainly before pulseaudio server starts.
The way I restart a container is through `docker run --restart always` so the container will restart just after the docker daemon starts.

I guess I will have to make pulseaudio run system wide if I don't want to login. 
And the container must start afterwards...but how to make sure this?

**Comment by mviereck** [comment] 2022-05-12 07:01
> The way I restart a container is through docker run --restart always

x11docker always drops the container after use so `--restart=always` is not possible. Or don't you use x11docker at all for your setup?

> I guess I will have to make pulseaudio run system wide if I don't want to login.
And the container must start afterwards...but how to make sure this?

Check the systemd service files. You could start a system wide pulseaudio with a systemd service and add a line like `After=pulseaudio.service` do the docker service.

**Comment by zwfcrazy** [comment] 2022-05-12 07:11
> Or don't you use x11docker at all for your setup?

Yes, I am using my own image as I don't need everything in x11docker. I was struggling about playing sound in a container until I found your wiki. It is very well written, thanks!

> Check the systemd service files. You could start a system wide pulseaudio with a systemd service and add a line like After=pulseaudio.service do the docker service.

This way looks promising, I will give it a try.

**Comment by mviereck** [comment] 2022-05-22 11:37
Closing for now. If you need further help, just ask.

**Closed by mviereck** 2022-05-22 11:37 UTC
Labels: question
