### ISSUE TITLE
use --user=root Startup failure

### ISSUE THREAD

**Issue by iptop** [mviereck/x11docker#42] opened 2018-05-02 01:32 UTC
I'm using deepin Linux

`x11docker --desktop   --user=root  --size 320x240 x11docker/lxde`

Unable to start successfully

[x11docker.log at pastebin](https://pastebin.com/H6WRwbhx)

**Comment by mviereck** [comment] 2018-05-02 09:32
Thanks for reporting!

I can reproduce this issue if I use option `--no-init` on my debian system. 
The deepin docker package seems to miss `/usr/bin/docker-init` as I see in your logfile. 
With `/usr/bin/docker-init` the issue does not appear.

Though, I am not sure about the reasons. Neither x11docker logfile nor LXDE logfile does show anything obvious. Same happens with `x11docker/xfce`.

Same happens with option `--sudouser` instead of `--user=root`.

I will investigate further and inform you if I find out something.

**Comment by mviereck** [comment] 2018-05-04 21:47
I have published a new release v4.2.0.

`x11docker --desktop --user=root --size 320x240 x11docker/lxde` will run now without any issue and without additional setup.

I'll close this issue. Feel free to reopen if you still have an issue.

Thanks again for reporting!

**Closed by mviereck** 2018-05-04 21:47 UTC
Labels: bug

**Comment by iptop** [comment] 2018-05-05 09:02
The problem is really solved in the new version
